### ISSUE TITLE
bhai ye design thoda change kardo iska ,kam achaa lag raha hai ,Pic daala hu kholo isko

### ISSUE THREAD

**Issue by Ashish-PalG** [trulyhuman/brbExpress#8]
![ui_change](https://user-images.githubusercontent.com/80711163/114299885-3a350280-9adb-11eb-962b-f704a8437536.PNG)

**Comment by gokunik** [comment]
ha bhai kerunga merko bhi acha nahi laga ek button hatana padega dono ache nahi lag rahe and color change kerna padega
. isko kerta hu bhad mai ek bar pura hojaye. ye issue bhi tabhi close ker dunga

**Comment by Ashish-PalG** [comment]
Okk bro 👍🏼

**Comment by gokunik** [comment]
![image](https://user-images.githubusercontent.com/57342034/114382924-931f9c00-9baa-11eb-88a4-bb7c7ef4a96d.png)
![image](https://user-images.githubusercontent.com/57342034/114383556-4be5db00-9bab-11eb-97da-61eea8a5a669.png)

Ye thik hai??

**Comment by Ashish-PalG** [comment]
Yeh perfect hai great work👍🏼👍🏼👍🏼👍🏼👍🏼

**Comment by gokunik** [comment]
ok then ye issue close kera hu mai. merko bhi ye sahi lagra hai
